#!/bin/bash

cd lede

(
    cd package
    git clone https://github.com/tuanqing/install-program
#     git clone https://github.com/tuanqing/openwrt-mentohust
#     git clone https://github.com/tuanqing/luci-app-mentohust
    git clone https://github.com/jerrykuku/luci-theme-argon -b 18.06
    git clone https://github.com/jerrykuku/luci-app-jd-dailybonus
    git clone https://github.com/jerrykuku/luci-app-ttnode
    git clone https://github.com/jerrykuku/luci-app-argon-config
    git clone https://github.com/lisaac/luci-lib-docker
    git clone https://github.com/lisaac/luci-app-dockerman

    sed -i 's/+docker-ce/+docker +dockerd/' luci-app-dockerman/applications/luci-app-dockerman/Makefile

    rm -rf libs/nettle
    rm -rf lean/{samba4,luci-app-samba4,luci-app-ttyd,luci-theme-argon,luci-lib-docker}
    svn co https://github.com/Lienol/openwrt/branches/main/package/libs/{libaudit,libsemanage,musl-fts,nettle} libs
)

cat >feeds.conf.default <<-EOF
src-git luci https://github.com/Lienol/openwrt-luci.git;18.06
src-git packages https://github.com/Lienol/openwrt-packages.git;main
src-git routing https://git.openwrt.org/feed/routing.git
src-git telephony https://git.openwrt.org/feed/telephony.git
src-git helloworld https://github.com/fw876/helloworld.git
src-git passwall_trojango https://github.com/goer99/xiaorouji-openwrt-passwall.git
EOF

./scripts/feeds update -a
./scripts/feeds install -a

git apply ../.github/patches/{0001*,0002*}.patch --directory=feeds/luci
(
    cd feeds/luci/modules/luci-mod-admin-full/luasrc/view/admin_status
    mv index.htm index.htm.old
    cp index_arm.htm index.htm
)

zzz="package/lean/default-settings/files/zzz-default-settings"
sed -i 's/samba/samba4/' $zzz
sed -i "/openwrt_luci/i sed -i '/Lienol/d' /etc/opkg/distfeeds.conf" $zzz
sed -i "/openwrt_luci/i sed -i '/helloworld/d' /etc/opkg/distfeeds.conf" $zzz

packages=" \
brcmfmac-firmware-43430-sdio brcmfmac-firmware-43455-sdio kmod-brcmfmac wpad \
kmod-fs-ext4 kmod-fs-vfat kmod-fs-exfat dosfstools e2fsprogs ntfs-3g \
kmod-usb2 kmod-usb3 kmod-usb-storage kmod-usb-storage-extras kmod-usb-storage-uas \
kmod-usb-net kmod-usb-net-asix-ax88179 kmod-usb-net-rtl8150 kmod-usb-net-rtl8152 \
blkid lsblk parted fdisk cfdisk losetup resize2fs tune2fs pv unzip \
lscpu htop iperf3 curl lm-sensors python3 install-program
"
sed -i '/FEATURES+=/ { s/cpiogz //; s/ext4 //; s/ramdisk //; s/squashfs //; }' \
    target/linux/armvirt/Makefile
for x in $packages; do
    sed -i "/DEFAULT_PACKAGES/ s/$/ $x/" target/linux/armvirt/Makefile
done

rm -f package/lean/shadowsocksr-libev/patches/0002-Revert-verify_simple-and-auth_simple.patch
sed -i '383,393 d' package/lean/shadowsocksr-libev/patches/0001-Add-ss-server-and-ss-check.patch
sed -i 's/PKG_RELEASE:=5/PKG_RELEASE:=6/' package/lean/shadowsocksr-libev/Makefile
sed -i '/PKG_SOURCE_VERSION:=/d' package/lean/shadowsocksr-libev/Makefile
sed -i '/PKG_SOURCE_URL/a PKG_SOURCE_VERSION:=4799b312b8244ec067b8ae9ba4b85c877858976c' \
    package/lean/shadowsocksr-libev/Makefile

# sed -i 's/ipaddr:-"192.168.1.1"/ipaddr:-"192.168.1.10"/' package/base-files/files/bin/config_generate

cat >.config <<-EOF
## target
CONFIG_TARGET_armvirt=y
CONFIG_TARGET_armvirt_64=y
CONFIG_TARGET_armvirt_64_Default=y
## luci app
CONFIG_PACKAGE_luci-app-adbyby-plus=y
CONFIG_PACKAGE_luci-app-aria2=y
CONFIG_PACKAGE_luci-app-cifs-mount=y
CONFIG_PACKAGE_luci-app-samba4=y
CONFIG_PACKAGE_luci-app-ttyd=y
#CONFIG_PACKAGE_luci-app-mentohust=y
CONFIG_PACKAGE_luci-app-dockerman=y
CONFIG_PACKAGE_luci-app-jd-dailybonus=y
CONFIG_PACKAGE_luci-app-ttnode=y
CONFIG_PACKAGE_luci-app-argon-config=y
## luci theme
CONFIG_PACKAGE_luci-theme-bootstrap-mod=y
CONFIG_PACKAGE_luci-theme-argon=y
## remove
# CONFIG_UnblockNeteaseMusic_NodeJS is not set
# CONFIG_PACKAGE_luci-app-webadmin is not set
## others
CONFIG_BRCMFMAC_SDIO=y
CONFIG_LUCI_LANG_en=y
## newly added
# 可选软件
CONFIG_PACKAGE_luci-app-firewall=y
CONFIG_PACKAGE_luci-app-frpc=y
CONFIG_PACKAGE_luci-app-frps=y
CONFIG_PACKAGE_luci-app-netdata=y
#-#CONFIG_PACKAGE_luci-app-docker=y
CONFIG_PACKAGE_luci-app-openvpn=y
CONFIG_PACKAGE_luci-app-openvpn-server=y
CONFIG_PACKAGE_luci-app-unblockNeteaseMusic=y
CONFIG_PACKAGE_luci-app-arpbind=y
CONFIG_PACKAGE_luci-app-ddns=y
CONFIG_PACKAGE_luci-app-ipsec-vpnd=y
CONFIG_PACKAGE_luci-app-vlmcsd=y
CONFIG_PACKAGE_luci-app-pptp-server=y
CONFIG_PACKAGE_luci-app-transmission=y
# ACC 网络加速（SFE）
CONFIG_PACKAGE_luci-app-sfe=y
CONFIG_PACKAGE_curl=y
CONFIG_PACKAGE_htop=y
CONFIG_PACKAGE_nano=y
CONFIG_PACKAGE_screen=y
CONFIG_PACKAGE_tree=y
CONFIG_PACKAGE_vim-fuller=y
CONFIG_PACKAGE_wget=y
CONFIG_PACKAGE_bash=y
## luci theme
CONFIG_PACKAGE_luci-theme-argon-dark-mod=y
CONFIG_PACKAGE_luci-theme-argon-light-mod=y
CONFIG_PACKAGE_luci-theme-bootstrap-mod=y
## remove
# CONFIG_UnblockNeteaseMusic_NodeJS is not set
# CONFIG_PACKAGE_luci-app-webadmin is not set
## others
CONFIG_BRCMFMAC_SDIO=y
CONFIG_LUCI_LANG_en=y
# add useful packages
CONFIG_PACKAGE_luci-app-netdata=y
CONFIG_PACKAGE_luci-app-adguardhome=y
CONFIG_PACKAGE_luci-app-airplay2=y
#-#CONFIG_PACKAGE_luci-app-amule=y
CONFIG_PACKAGE_luci-app-baidupcs-web=y
#-#CONFIG_PACKAGE_luci-app-dnsforwarder=y
#-#CONFIG_PACKAGE_luci-app-docker=y
CONFIG_PACKAGE_luci-app-familycloud=y
CONFIG_PACKAGE_luci-app-filebrowser=y
CONFIG_PACKAGE_luci-app-frpc=y
CONFIG_PACKAGE_luci-app-frps=y
CONFIG_PACKAGE_luci-app-guest-wifi=y
CONFIG_PACKAGE_luci-app-haproxy-tcp=y
CONFIG_PACKAGE_luci-app-hd-idle=y
CONFIG_PACKAGE_luci-app-kcptun=y
CONFIG_PACKAGE_luci-app-mwan3=y
CONFIG_PACKAGE_luci-app-mwan3helper=y
CONFIG_PACKAGE_luci-app-n2n_v2=y
CONFIG_PACKAGE_luci-app-nfs=y
CONFIG_PACKAGE_luci-app-openvpn=y
CONFIG_PACKAGE_luci-app-openvpn-server=y
CONFIG_PACKAGE_luci-app-passwall=y
# Passwall Configuration
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ipt2socks=y
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks=y
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR=y
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Server=y
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray=y
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan=y
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_GO=y
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Brook=y
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_kcptun=y
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_haproxy=y
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ChinaDNS_NG=y
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_pdnsd=y
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_dns2socks=y
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_v2ray-plugin=y
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_simple-obfs=y
# end of Passwall Configuration
# Compression
CONFIG_PACKAGE_gzip=y
CONFIG_PACKAGE_unrar=y
CONFIG_PACKAGE_unzip=y
CONFIG_PACKAGE_zip=y
# Disc
CONFIG_PACKAGE_badblocks=y
CONFIG_PACKAGE_blkid=y
CONFIG_PACKAGE_cfdisk=y
CONFIG_PACKAGE_cgdisk=y
CONFIG_PACKAGE_eject=y
CONFIG_PACKAGE_fdisk=y
CONFIG_PACKAGE_hdparm=y
CONFIG_PACKAGE_lsblk=y
CONFIG_PACKAGE_lvm2=y
CONFIG_PACKAGE_resize2fs=y
# timezone
CONFIG_PACKAGE_zoneinfo-asia=y
CONFIG_PACKAGE_trojan=y
CONFIG_PACKAGE_trojan-go=y
#
# Configuration
#
# CONFIG_TROJAN_GO_COMPRESS_GOPROXY is not set
CONFIG_TROJAN_GO_COMPRESS_UPX=y
### newly added end
EOF

make defconfig
cat .config
